http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  usersEndpoint:
    host: localhost
    paths: '/users'
  api:
    host: localhost
    paths: '/ip'
serviceEndpoints:
  usersService:
    url: 'http://localhost:3001'
  httpbin:
    url: 'https://httpbin.org'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true
  usersPipeline:
    apiEndpoints:
      - usersEndpoint
    policies:
      - proxy:
        - action:
            serviceEndpoint: usersService
            changeOrigin: false
